name: Run System Tests
on: workflow_call

jobs:
  run-system-steps:
    runs-on: ubuntu-latest
    name: Run system tests
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          cd ghap/build 
          cmake . && make

      - name: Move binary to system tests directory
        run: |
          cd ghap && mv ./build/basic-calculator ./system-test/basic-calculator
          cd ./system-test

      - name: Run system tests
        run: |
          cd ghap/system-test
          cmake . && make
          ./system-tests
          ls -al
