# .github/workflows/build-and-push-docker-image.yaml
name: Build and push Docker image


on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4.2.2

      - name: Set environment variables
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/testing:$TIMESTAMP
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -t $IMAGE_NAME ./ghap

      - name: List Docker images
        run: docker images

      - name: Test Docker image
        run: docker run $IMAGE_NAME ./basic-calculator divide 2 3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME


