name: Child 1
on: workflow_call

jobs:
  job-0:
    runs-on: ubuntu-latest
    name: Job zero
    steps:
      - run: echo "Hello"

  job-1:
    runs-on: ubuntu-latest
    name: Job one
    needs: job-0
    strategy:
      matrix:
        python-version: [3.12, 3.04]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}' 
      - run: python --version



  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    name: Job two
    steps:
      - run: echo "Job 2"


