name: Child Workflow 1

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  child1-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Image Name
        run: echo "Image name is ${{ inputs.image-name }}"
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Step 3
        run: echo "Child 1 - Job 1 - Step 3"

  child1-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Child 1 Job 2
        run: echo "Child 1 - Job 2 - Step 1"
      - name: Step 2 in Child 1 Job 2
        run: echo "Child 1 - Job 2 - Step 2"

