name: Child 1
on: workflow_call

jobs:
  job-1:
    runs-on: ubuntu-latest
    name: Job one
    steps:
      - run: echo "Job 1"


  job-2:
    runs-on: ubuntu-latest
    name: Job two
    steps:
      - run: echo "Job 2"


