name: Child Workflow 1

on:
  workflow_call:

jobs:
  child1-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Child 1 Job 1
        run: echo "Child 1 - Job 1 - Step 1"
      - name: Step 2 in Child 1 Job 1
        run: echo "Child 1 - Job 1 - Step 2"
      - name: Step 3 in Child 1 Job 1
        run: echo "Child 1 - Job 1 - Step 3"

  child1-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Child 1 Job 2
        run: echo "Child 1 - Job 2 - Step 1"
      - name: Step 2 in Child 1 Job 2
        run: echo "Child 1 - Job 2 - Step 2"


