name: Child 1 Workflow
on: workflow_call

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1"
      - name: Step 2
        run: echo "Step 2"


  grand-child-one-one:
    uses: ./github/workflows/gchild11.yaml

  grand-child-one-two:
    uses: ./github/workflows/gchild12.yaml
