name: Child 1
on: workflow_call

jobs:
  job-1:
    runs-on: ubuntu-latest
    name: Job one
    strategy:
      matrix:
        key1: [value1, value2]
    steps:
      - run: echo "${{ matrix.key1 }}"


  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    name: Job two
    steps:
      - run: echo "Job 2"


