name: Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find all
        run: find ./ -type d | sed 's/[^\/]*\//|   /g;s/|   \([^|]\)/+-- \1/'
      # Buld the cpp app
      - name: Build
        run: cd ghap/build && ls -al && cmake . && make
      # Run the cpp app
      - name: Run
        run: cd ghap/build && ./basic-calculator add 1 2

  second-job:
    name: Second Job
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Hello from the second step"

  third-job:
    name: Third job
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Hello from the third job"
