name: Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: First step
        run: ls -al
      - name: Second step
        run: echo "Hello from second step"

  second-job:
    name: Second Job
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Hello from the second step"

  third-job:
    name: Third job
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Hello from the third job"
