name: Parent workflow
on: push

jobs:
  child-one-job:
    name: Child job 1
    uses: ./.github/workflows/child1.yaml

  child-two-job:
    name: Child job 2
    uses: ./.github/workflows/child2.yaml

