name: Matrix Strategy testing

on:
  push:
    branches:
      - main


jobs:
  initial-setup-job:
    runs-on: ubuntu-latest
    name: Initial setup Job
    steps:
      - run: echo "Initial setup Job"


  matrix-job:
    runs-on: ubuntu-latest
    name: Matrix Job
    needs: initial-setup-job

    strategy:
      matrix:
        #These key value pairs can be anything we want#
        dummy-key: [dummy-value1, dummy-value2]
        #/These key value pairs can be anything we want#


    steps:
      - run: echo "${{ toJSON(matrix) }}"


  conclude-job:
    runs-on: ubuntu-latest
    name: Conclude job
    needs: matrix-job
    steps:
      - run: echo "Conclude job"


