name: Matrix Strategy testing

on:
  push:
    branches:
      - main


jobs:
  first-job:
    runs-on: ubuntu-latest
    name: First Job
    steps:
      - run: echo "First job"


  second-job:
    runs-on: ubuntu-latest
    name: Second Job
    needs: first-job

    strategy:
      matrix:
        #These key value pairs can be anything we want#
        dummy-key: [dummy-value1, dummy-value2]
        sample-key: [sample-value1, sample-value2]
        #/These key value pairs can be anything we want#


    steps:
      - run: echo "${{ toJSON(matrix) }}"


  third-job:
    runs-on: ubuntu-latest
    name: Third Job
    needs: second-job
    steps:
      - run: echo "Third job"


