name: Matrix Strategy testing

on:
  push:
    branches:
      - main


jobs:
  initial-setup-job:
    runs-on: ubuntu-latest
    name: Initial setup job
    steps:
      - run: echo "Initial setup job"


      
  pythonV3-13-setup-windows:
    name: Python v3.13 setup in windows
    runs-on: windows-latest
    needs: initial-setup-job

    steps:
      - name: Setup Python version v3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - run: python --version
     

  pythonV3-11-setup-windows:
    name: Python v3.11 setup in windows
    runs-on: windows-latest
    needs: initial-setup-job


    steps:
      - name: Setup Python version v3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python --version

  pythonV3-13-setup-ubuntu:
    name: Python v3.13 setup in Ubuntu
    runs-on: ubuntu-latest
    needs: initial-setup-job

    steps:
      - name: Setup Python version v3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: python --version

 
  pythonV3-11-setup-ubuntu:
    name: Python v3.11 setup in Ubuntu
    runs-on: ubuntu-latest
    needs: initial-setup-job

    steps:
      - name: Setup Python version v3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python --version





    
  cleanup-job:
    runs-on: ubuntu-latest
    name: Cleanup job
    needs:
      - pythonV3-13-setup-windows
      - pythonV3-11-setup-windows
      - pythonV3-13-setup-ubuntu
      - pythonV3-11-setup-ubuntu

    steps:
      - run: echo "Cleanup job"



