name: Matrix Strategy testing

on:
  push:
    branches:
      - main


jobs:
  initial-setup-job:
    runs-on: ubuntu-latest
    name: Initial setup job
    steps:
      - run: echo "Initial setup job"


  use-python-setup:
    name: Use Python setup
    needs: initial-setup-job

    strategy:
      matrix:
        #These key value pairs can be anything we want#
        python-version: [3.13, 3.11]
        operating-system: [ubuntu-latest, windows-latest]
        #/These key value pairs can be anything we want#

    runs-on: ${{ matrix.operating-system }}
    
    steps:
      - name: Setup Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      
    
  cleanup-job:
    runs-on: ubuntu-latest
    name: Cleanup job
    needs: use-python-setup
    steps:
      - run: echo "Third job"


