name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  job-in-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Parent
        run: echo "Step 1"
      - name: Step 2 in Parent
        run: echo "Step 2"
      - name: Step 3 in Parent
        run: echo "Step 3"

  call-child-1:
    uses: ./.github/workflows/child1.yaml
    with:
      image-name: "my-app"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  call-child-2:
    uses: ./.github/workflows/child2.yaml
    with:
      image-name: "my-app"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

