name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  job-in-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Parent
        run: echo "Step 1"
      - name: Step 2 in Parent
        run: echo "Step 2"
      - name: Step 3 in Parent
        run: echo "Step 3"

  call-child-1:
    needs: job-in-parent
    uses: ./.github/workflows/child1.yaml

  call-child-2:
    needs: call-child-1
    uses: ./.github/workflows/child2.yaml


