name: Matrix Strategy testing

on:
  push:
    branches:
      - main


jobs:
  first-job:
    runs-on: ubuntu-latest
    name: First Job
    steps:
      - run: echo "First job"


  second-job:
    runs-on: ubuntu-latest
    name: Second Job
    needs: first-job

    strategy:
      matrix:
        #These key value pairs can be anything we want#
        dummy-key: [dummy-values1, dummy-values2]
        #/These key value pairs can be anything we want#


    steps:
      - run: echo matrix.strategy.dummy-key


  third-job:
    runs-on: ubuntu-latest
    name: Third Job
    needs: second-job
    steps:
      - run: echo "Third job"

