name: Push to main
on:
  push:
    branches:
      - main


jobs:

  clone-and-run-unit-tests:
    runs-on: ubuntu-latest
    name: Clone and run Unit-Tests
    steps:
      - run: echo "Clone and run unit tests"


  unit-tests-failed:
    needs: clone-and-run-unit-tests
    if: failure()
    runs-on: ubuntu-latest
    name: Unit tests failed
    steps:
      - run: echo "Unit tests failed"


  build-binary-and-run-system-tests:
    needs: clone-and-run-unit-tests
    runs-on: ubuntu-latest
    name: Build binary and run System Tests
    steps:
      - run: echo "Building and running system tests"

  system-tests-failed:
    needs: build-binary-and-run-system-tests
    if: failure()
    runs-on: ubuntu-latest
    name: System tests failed
    steps:
      - run: echo "System tests failed"


  build-docker-image-and-push-to-docker-hub:
    needs: build-binary-and-run-system-tests
    runs-on: ubuntu-latest
    name: Build Docker image and push to Dockerhub
    steps:
      - run: echo "Building Docker image and push to Dockerhub"



