name: Testing Cascading Steps
on: push

jobs:
  # JOB 1
  job-one:
    runs-on: ubuntu-latest
    name: "Job 1"
    steps:

      # Checkout code
      - uses: actions/checkout@v4

      # Step 1
      - name: Step 1
        run: echo "Running Step 1"

      # Step 2
      - name: Step 2
        run: echo "Running Step 2"


  # JOB 2
  job-two:
    runs-on: ubuntu-latest
    name: "Job 2"
    steps:

      # Checkout code
      - uses: actions/checkout@v4

      - name: Step 1
        run: echo "Running Step 1"

      # Step 2
      - name: Step 2
        run: echo "Running Step 2"


























