name: Testing Cascading Steps

on: push

jobs:
  # JOB 1
  job-one:
    runs-on: ubuntu-latest
    name: "Build docker image"
    steps:
      - uses: actions/checkout@v4.2.2
      - run: |
          cd ghap
          ls -al
          docker build -t testing .
      - name: List Docker images
        run: docker images
      - name: Test Docker image
        run: docker run testing
