name: Testing Cascading Steps
on: push

jobs:
  job-one:
    runs-on: ubuntu-latest
    name: "Job 1"
    continue-on-error: true 
    steps:
      - uses: actions/setup-node@v3.9.1
      - run: node --version






