name: Testing Cascading Steps

on: push

jobs:
  # JOB 1
  job-one:
    runs-on: ubuntu-latest
    name: "Build docker image"
    steps:
      - uses: actions/checkout@v4.2.2
      - run: |
          cd ghap
          ls -al
