name: Run System Tests
on:
  push:
    branches:
      - main

jobs:
  run-system-steps:
    runs-on: ubuntu-latest
    name: Run system tests
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          cd ghap/build 
          cmake . && make
          ls -l



