name: Testing Cascading Steps

on: push

jobs:
  # JOB 1
  job-one:
    runs-on: ubuntu-latest
    name: "Build docker image"
    steps:
      # Clone the repo
      - uses: actions/checkout@v4.2.2

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t testing ./ghap

      # List existing Docker images
      - name: List Docker images
        run: docker images

      # Test Docker image
      - name: Test Docker image
        run: docker run testing ./basic-calculator divide 2 0
