name: Pipeline job

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  clone-and-run-system-tests:
    name: Clone and run system tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: List all
        run: ls -al && tree -a

      - name: Build Binary
        run: |
          cd ghap/build
          cmake . && make
          ls -al


