name: Testing Cascading Steps
on: push

jobs:
  job-one:
    runs-on: ubuntu-latest
    name: "Job 1"
    steps:


      # Step 1
      - name: Step 1
        run: echo "ok"

      # Step 2
      - name: Step 2
        run: exit 1

      # Step 3
      - name: Step 3
        run: echo "ok"


      # Step 4
      - name: Step 3 error handler
        if: failure()

        run: echo "${{ steps }}"


      # Step 5
      - name: Step 5
        run: echo "ok"
