name: Pipeline job

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  clone-and-run-unit-tests:
    name: Clone and run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: actions/checkout@v4
      - name: List all
        run: ls -al && tree -a

      - name: Run unit tests
        run: |
          cd ghap/test
          cmake && make
          ./unit-tests


