name: Testing Cascading Steps
on: push

jobs:
  job-one:
    runs-on: Ubuntu
    name: "Testing cas"
    steps:

      # Step 1
      - name: Step 1
        run: echo "Running step 1"

      # Step 2
      - name: Step 2
        run: echo "Running step 2"

      # Step 3
      - name: Step 3
        run: echo "Running step 3"


      # Step 4
      - name: Step 4
        run: echo "Running step 4"


      # Step 5
      - name: Step 5
        run: echo "Running step 5"



























