name: Testing Cascading steps
on: push

jobs:
  job-one:
    runs-on: ubuntu-latest
    name: "Sample Job"
    steps:


      # Step 1
      - name: Step 1
        run: echo ""


      # Step 2
      - name: Step 2
        run: echo "ok"

      # Step 3
      - name: Step 3
        run: exit 1
        continue-on-error: true


      

      - name: Step 3 error handler
        run: echo ""


      # Step 4
      - name: Step 4
        run: echo "ok"


      # Step 5
      - name: Step 5
        run: echo "ok"
