name: Push to master

on: push

jobs:

  first-job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: "First step"
        run: echo "Hello from first step"


  second-job:
    runs-on: ubuntu-latest
    name: Second Job
    needs: first-job
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: First step
        run: |
          cd ghap/build && \
          ls -al && \
          cmake . && \
          make && \
          ./basic-calculator add 2 3

      - name: Second step
        run: echo "Hello world"

