name: Testing Cascading Steps
on: push

jobs:
  job-one:
    runs-on: ubuntu-latest
    name: "Job 1"
    steps:


      # Step 1
      - name: Step 1
        run: exit code 1


      # Step 2
      - name: Step 2
        run: echo "ok"

      # Step 3
      - name: Step 3
        id: step-3-id
        run: echo ""


      

      - name: Step 3 error handler
        if: failure() && steps.step-3-id.outcome == 'failure'
        run: |
          echo "Handle step 3"


      # Step 4
      - name: Step 4
        run: echo "ok"


      # Step 5
      - name: Step 5
        run: echo "ok"
